{% set name = "pelegant" %}
{% set version = "2023.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://ops.aps.anl.gov/downloads/elegant.{{ version }}.tar.gz
    sha256: 48efea2f34d055807f7ae6b31c1f115ab75730743c1c238873fa9c83e8f48085
    folder: src/elegant
  - url: https://ops.aps.anl.gov/downloads/oag.apps.configure.tar.gz
    sha256: eef0912a70b069e55d1df24cd008f42e6a5923e35461f2b69f92cd1e7e2d4596
    folder: src/oag-apps
  - url: https://ops.aps.anl.gov/downloads/SDDS.5.5.tar.gz
    sha256: c07823e10ba75bea4d6277a2cddf126f366e4ea563fea3967dd8268c7a13be2a
    folder: src/sdds
  - url: https://ops.aps.anl.gov/downloads/epics.base.configure.tar.gz
    sha256: d18a5a1dd58ab485df32a55a32f0f2a7517b6a5361439208dc38d2fe69f6e22e
    folder: src/epics-base
  - url: https://ops.aps.anl.gov/downloads/epics.extensions.configure.tar.gz
    sha256: 46db83bf7e0cc70be663a822e4cb229cb03f52e98e6920fbc1ce181df9eac59b
    folder: src/epics-extensions

build:
  skip: true  # [win]
  number: 0
  ignore_run_exports:
    # libsz/libaec used in hdf2sdds/sdds2hdf:
    - libaec
    - libopenblas  # [osx]
    - python
    # Darwin-only; linked in sdds2tiff/tiff2sdds
    - zstd  # [osx]


requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }}
    - mpich
    - make
  host:
    - blas
    - blis  # [linux]
    - fftw * mpi_mpich_*
    - gsl
    - hdf5 * mpi_mpich_*
    - libaec
    - libgomp  # [linux]
    - mpi * mpich*
    - mpich
    - ncurses
    - openmp  # [linux]
    - python =3.10
    - xz
    - zlib
    - zstd  # [osx]
  run:
    # blas for liblapacke
    - blas
    # Pelegant itself links to blis on Linux only
    - blis  # [linux]
    - fftw * mpi_mpich_*
    - gsl
    - hdf5 * mpi_mpich_*
    - libgomp  # [linux]
    - mpi * mpich*
    - mpich
    - ncurses
    - openmp  # [linux]
    - python =3.10
    - xz

test:
  imports:
    - sdds
    - sddsdata
  commands:
    - which Pelegant
    - Pelegant
    # These are skipped on macOS at the moment - sddscontour:
    - which sddscontour  # [linux]
    - which sddscongen  # [linux]
    - which sddshist2d  # [linux]
    - which sddsimageconvert  # [linux]
    # These are skipped on macOS at the moment - pseudoInverse:
    - which sdds2dpfit  # [linux]
    - which sddsica  # [linux]
    - which sddsmatrixop  # [linux]
    - which sddspseudoinverse  # [linux]
    # Pelegant supporting applications:
    - which TFS2sdds
    - which applicationBrowse
    - which applicationPatch
    - which applicationSubmit
    - which beamlineDownTime
    - which carriageReturn2newline
    - which checkRequestFile
    - which citi2sdds
    - which clearPatch
    - which col2sdds
    - which convert_to_bdd
    - which csv2sdds
    - which editstring
    - which elegant2genesis
    - which hdf2sdds
    - which hpif2sdds
    - which hpwf2sdds
    - which if2pf
    - which image2sdds
    - which isFileLocked
    - which lba2sdds
    - which mcs2sdds
    - which mecho
    - which minpath
    - which mpl2sdds
    - which nlpp
    - which normalizeFlagData
    - which plaindata2sdds
    - which pvsearch
    - which raw2sdds
    - which replace
    - which replaceText
    - which rpn
    - which rpnl
    - which runAPSStartSROrbitControllaw
    - which sdds2dfft
    - which sdds2dinterpolate
    - which sdds2hdf
    - which sdds2headlessdata
    - which sdds2math
    - which sdds2mpl
    - which sdds2plaindata
    - which sdds2spreadsheet
    - which sdds2stl
    - which sdds2stream
    - which sdds2tiff
    - which sddsDiskUsage
    - which sddsanalyticsignal
    - which sddsarray2column
    - which sddsbaseline
    - which sddsbinarystring
    - which sddsbreak
    - which sddscast
    - which sddschanges
    - which sddscheck
    - which sddscliptails
    - which sddscollapse
    - which sddscollect
    - which sddscombine
    - which sddscombinelogfiles
    - which sddsconvert
    - which sddsconvertlogonchange
    - which sddsconvolve
    - which sddscorrelate
    - which sddsderef
    - which sddsderiv
    - which sddsdiff
    - which sddsdigfilter
    - which sddsdistest
    - which sddsduplicate
    - which sddsendian
    - which sddsenvelope
    - which sddseventhist
    - which sddsexpand
    - which sddsexpfit
    - which sddsfdfilter
    - which sddsfft
    - which sddsfindin2dgrid
    - which sddsgenericfit
    - which sddsgfit
    - which sddshist
    - which sddsimageprofiles
    - which sddsinsideboundaries
    - which sddsinteg
    - which sddsinterp
    - which sddsinterpset
    - which sddslogclient
    - which sddslogserver
    - which sddslorentzianfit
    - which sddsmakedataset
    - which sddsmatrix2column
    - which sddsmatrixmult
    - which sddsminterp
    - which sddsmpfit
    - which sddsmselect
    - which sddsmultihist
    - which sddsmxref
    - which sddsnaff
    - which sddsnormalize
    - which sddsoutlier
    - which sddspeakfind
    - which sddspfit
    - which sddsplot
    - which sddspoly
    - which sddsprintout
    - which sddsprocess
    - which sddsquery
    - which sddsregroup
    - which sddsremoveoffsets
    - which sddsrespmatrixderivative
    - which sddsrowstats
    - which sddsrunstats
    - which sddssampledist
    - which sddsselect
    - which sddsseparate
    - which sddssequence
    - which sddsshift
    - which sddsshiftcor
    - which sddssinefit
    - which sddsslopes
    - which sddssmooth
    - which sddssnap2grid
    - which sddssort
    - which sddssortcolumn
    - which sddssplit
    - which sddsspotanalysis
    - which sddstdrpeeling
    - which sddstimeconvert
    - which sddstranspose
    - which sddsunwrap
    - which sddsvslopes
    - which sddsxref
    - which sddszerofind
    - which startFirefox
    - which tcomp
    - which tdms2sdds
    - which tek2sdds
    - which testlock
    - which tiff2sdds
    - which timeconvert
    - which tmpname
    - which token
    - which wfm2sdds

about:
  home: https://www.aps.anl.gov/Accelerator-Operations-Physics/Software
  license: EPICS
  license_file: oag/apps/src/elegant/LICENSE
  summary: |
    Pelegant is Parallel Elegant, a parallelized accelerator code that
    computes beta functions, matrices, orbits, floor coordinates, amplification
    factors, dynamic aperture, and more
  description: |
    Elegant is an accelerator code that computes beta functions, matrices,
    orbits, floor coordinates, amplification factors, dynamic aperture, and
    more. It does 6-D tracking with matrices and/or canonical integrators, and
    supports a variety of time-dependent elements. It also does optimization
    (e.g., matching), including optimization of tracking results. It is the
    principle accelerator code used at APS.
  doc_url: https://ops.aps.anl.gov/manuals/elegant_latest/elegant.html
  dev_url: https://www.aps.anl.gov/Accelerator-Operations-Physics/Software

extra:
  recipe-maintainers:
    - ken-lauer
